#!/usr/bin/env bash
# Download the webfonts and emit a local @font-face stylesheet.
#
# The buyer-facing pages loaded these straight from fonts.googleapis.com, which
# hands Google the IP address of every visitor — on the checkout page, before
# they have agreed to anything. Self-hosting removes that third party entirely,
# and removes a DNS lookup plus TLS handshake from the critical path.
#
# Run once; the files are committed. Re-run only to change weights.
set -euo pipefail

OUT_DIR="$(cd "$(dirname "$0")/.." && pwd)/public/fonts"
CSS_OUT="$OUT_DIR/fonts.css"
mkdir -p "$OUT_DIR"

# A modern UA, or Google serves the older ttf/eot formats instead of woff2.
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36"

FAMILIES=(
  "Inter:wght@400;500;600;700"
  "Outfit:wght@500;600;700;800"
  "IBM+Plex+Mono:wght@500;600"
)

# Collected into a FILE, not a variable piped in: the python below uses a
# heredoc, which already owns stdin, so a pipe would silently deliver nothing.
RAW="$(mktemp)"
trap 'rm -f "$RAW"' EXIT
for spec in "${FAMILIES[@]}"; do
  curl -s --max-time 30 -A "$UA" "https://fonts.googleapis.com/css2?family=${spec}&display=swap" >> "$RAW"
  printf '\n' >> "$RAW"
done

# Latin only. The full set carries Cyrillic, Greek and Vietnamese that a
# Nigerian storefront will not render, and each is another file to download.
python3 - "$CSS_OUT" "$OUT_DIR" "$RAW" <<'PY'
import re, sys, subprocess, pathlib

css_out, out_dir = sys.argv[1], pathlib.Path(sys.argv[2])
raw = pathlib.Path(sys.argv[3]).read_text(encoding="utf-8")

blocks = re.findall(r"/\*\s*([a-z\-]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", raw)
keep, seen = [], set()
for subset, block in blocks:
    if subset not in ("latin", "latin-ext"):
        continue
    m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
    if not m:
        continue
    url = m.group(1)
    name = url.rsplit("/", 1)[-1]
    if name not in seen:
        seen.add(name)
        subprocess.run(["curl", "-sL", "--max-time", "30", "-o", str(out_dir / name), url], check=True)
    keep.append(block.replace(url, f"/fonts/{name}"))

header = (
    "/* Self-hosted webfonts.\n"
    " *\n"
    " * Generated by scripts/self-host-fonts.sh — do not edit by hand.\n"
    " *\n"
    " * These used to load from fonts.googleapis.com, which sent every buyer's\n"
    " * IP to Google before they had agreed to anything, on the page where they\n"
    " * type a phone number. Serving them ourselves removes that third party and\n"
    " * a DNS + TLS round trip from the critical path.\n"
    " */\n"
)
pathlib.Path(css_out).write_text(header + "\n".join(keep) + "\n", encoding="utf-8")
print(f"  {len(keep)} @font-face rules, {len(seen)} files")
PY
